### PR TITLE
Add new clock texture - HEL-71

### PR DESCRIPTION
**Pull request by nikolas**
This is showing up better in FF than Chrome for me. I'm curious to see
how this looks on a retina display, especially since I set `autoDensity`
to `true`.

The svg earthmap is still in progress.

### CODE REVIEW

**Comment by nikolas** [comment]
The clock is still fuzzier than it should be on my iPad :-/

Still, this can be reviewed and merged since I'm moving in the right direction with SVG.

**Comment by nikolas** [comment]
What I really need to do here is just double the dimensions of each pixi + three.js scene here and scale them down with CSS. At least now I have an iPad to see the problem.

**Comment by nikolas** [comment]
Alright, I doubled the entire clock scene's resolution and it's looking good now on both displays.

**Comment by sdreher** [comment]
Much sharper on my retina display as well.

**Pull request merged**
